[tools]
bun = "1.4.2"

# Dependencies

[tasks.deps]
depends = ["deps:frontend"]

[tasks."deps:frontend"]
dir = "frontend"
run = "bun install"

# Dev

[tasks.dev]
depends = ["dev:frontend"]

[tasks."dev:frontend"]
dir = "frontend"
run = "bun dev --open"
