[tools]
bun = "1.4.2"
dotnet = "10.0.400"

# Dependencies

[tasks.deps]
depends = ["deps:frontend", "deps:backend"]

[tasks."deps:frontend"]
dir = "frontend"
run = "bun install"

[tasks."deps:backend"]
dir = "backend"
run = "dotnet restore"

# Dev

[tasks.dev]
description = "Run both frontend and backend development servers concurrently"
depends = ["dev:frontend", "dev:backend"]

[tasks."dev:frontend"]
description = "Run the frontend development server"
dir = "frontend"
run = "bun dev --open"

[tasks."dev:backend"]
description = "Run the backend development server"
dir = "backend"
run = "dotnet watch"

# Formatting

[tasks.fmt]
description = "Format both frontend and backend code"
depends = ["fmt:frontend", "fmt:backend"]

[tasks."fmt:frontend"]
description = "Format the frontend code"
dir = "frontend"
run = "bun run fmt"

[tasks."fmt:backend"]
description = "Format the backend code"
run = "dotnet csharpier format backend"
